# src/app/resources/telegram/settings.yaml
title: Telegram
version: 2
help:
  short: Настройка Telegram-сессии и до 5 индивидуальных ролей
  long: |
    В одной сессии можно настроить до пяти разных ролей (учитель, ассистент, консультант и т.д.).
    Каждая роль имеет собственные промпты и режимы работы, а общие параметры сессии остаются едиными.

template:
  session:
    active: false
    whitelist: []
    blacklist: []
    history_limit: 20
  roles:
    - name: ""
      description: ""
      system_prompt: ""
      modes:
        lesson: ""
        dialogue: ""
        quiz: ""
        translate: ""
      temperature: 0.7
      top_p: 1.0
      max_tokens: 1024
      voice_enabled: true

schema:
  version: 2
  groups:
    - title: "⚙️ Общие настройки сессии"
      fields:
        - key: session.active
          label: "Активна ли сессия"
          type: boolean
          required: true
        - key: session.whitelist
          label: "Белый список пользователей"
          type: list
          required: false
        - key: session.blacklist
          label: "Черный список пользователей"
          type: list
          required: false
        - key: session.history_limit
          label: "Длина истории сообщений"
          type: number
          required: true

    - title: "🎭 Роли (до 5 штук)"
      fields:
        - key: roles
          label: "Роли"
          type: list
          required: false
          item_schema:
            name: string
            description: string
            system_prompt: textarea
            modes:
              lesson: string
              dialogue: string
              quiz: string
              translate: string
            temperature: number
            top_p: number
            max_tokens: number
            voice_enabled: boolean
