"""init: create tg_accounts

Revision ID: 165ab7be38b4
Revises: 
Create Date: 2025-08-17 10:47:07.916774

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '165ab7be38b4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('app_hash', sa.Text(), nullable=False),
    sa.Column('string_session', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'active', 'paused', 'blocked', 'invalid', name='tg_account_status'), server_default='new', nullable=False),
    sa.Column('reply_policy', sa.Enum('dm_only', 'mentions_only', 'read_only', name='tg_account_reply_policy'), server_default='dm_only', nullable=False),
    sa.Column('twofa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164'),
    sa.UniqueConstraint('tg_user_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_accounts')
    # ### end Alembic commands ###
