"""add status to messages

Revision ID: 1e9938985fcd
Revises: 2421a49e5e68
Create Date: 2025-08-14 11:40:31.465052

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1e9938985fcd'
down_revision = '2421a49e5e68'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.Text(), server_default='new', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
