"""dialogs + messages

Revision ID: 214eb7dd1ee4
Revises: 651c35cf68c2
Create Date: 2026-02-11 16:34:57.162999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '214eb7dd1ee4'
down_revision = '651c35cf68c2'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('thread_key', sa.Text(), nullable=False),
    sa.Column('peer_type', sa.Text(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('graph_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rag_cache', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'thread_key', name='uq_dialogs_resource_thread_key')
    )
    op.create_index('ix_dialogs_resource_last_message_at', 'dialogs', ['resource_id', 'last_message_at'], unique=False)
    op.create_index('ix_dialogs_resource_peer', 'dialogs', ['resource_id', 'peer_id'], unique=False)
    op.add_column('messages', sa.Column('dialog_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('messages', sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.drop_constraint(op.f('uq_messages_provider_chat_msg'), 'messages', type_='unique')
    op.create_index('ix_messages_dialog_created_at', 'messages', ['dialog_id', 'created_at'], unique=False)
    op.create_index('ix_messages_resource_peer_created_at', 'messages', ['resource_id', 'peer_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_messages_provider_resource_chat_msg', 'messages', ['provider', 'resource_id', 'external_chat_id', 'external_msg_id'])
    op.create_foreign_key(None, 'messages', 'dialogs', ['dialog_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint('uq_messages_provider_resource_chat_msg', 'messages', type_='unique')
    op.drop_index('ix_messages_resource_peer_created_at', table_name='messages')
    op.drop_index('ix_messages_dialog_created_at', table_name='messages')
    op.create_unique_constraint(op.f('uq_messages_provider_chat_msg'), 'messages', ['provider', 'external_chat_id', 'external_msg_id'])
    op.drop_column('messages', 'meta_json')
    op.drop_column('messages', 'is_internal')
    op.drop_column('messages', 'dialog_id')
    op.drop_index('ix_dialogs_resource_peer', table_name='dialogs')
    op.drop_index('ix_dialogs_resource_last_message_at', table_name='dialogs')
    op.drop_table('dialogs')
    # ### end Alembic commands ###
