"""create users

Revision ID: 6e79614b2f16
Revises: REPLACE_ME
Create Date: 2025-08-22 11:13:28.855710

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6e79614b2f16'
down_revision = 'REPLACE_ME'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updates_seen')
    op.add_column('messages', sa.Column('author', sa.Text(), nullable=False))
    op.add_column('messages', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('messages', sa.Column('status', sa.Text(), server_default='new', nullable=False))
    op.add_column('messages', sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_messages_account_peer_created', table_name='messages')
    op.drop_constraint('fk_messages_account', 'messages', type_='foreignkey')
    op.drop_column('messages', 'peer_type')
    op.drop_column('messages', 'latency_ms')
    op.drop_column('messages', 'tokens_in')
    op.drop_column('messages', 'peer_id')
    op.drop_column('messages', 'direction')
    op.drop_column('messages', 'tokens_out')
    op.drop_column('messages', 'text')
    op.drop_column('messages', 'account_id')
    op.drop_column('messages', 'msg_type')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'msg_id')
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('msg_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('msg_type', sa.TEXT(), server_default=sa.text("'text'::text"), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('tokens_out', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('peer_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('tokens_in', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('peer_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_messages_account', 'messages', 'tg_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_messages_account_peer_created', 'messages', ['account_id', 'peer_id', 'created_at'], unique=False)
    op.drop_column('messages', 'ts')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'author')
    op.create_table('updates_seen',
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tg_accounts.id'], name='fk_updates_seen_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'chat_id', 'message_id', name='pk_updates_seen')
    )
    # ### end Alembic commands ###
