# OpenAI settings (MVP)
model: gpt-4o-mini
temperature: 0.5
max_tokens_reply: 500

system_prompt: |
  Отвечай кратко и по делу. Пиши на языке пользователя (RU/AZ/EN).
  Если вопрос расплывчатый — попроси одно уточнение. Избегай навязчивости и маркетинга.
  Не разглашай внутренние детали реализации.

timeouts:
  request_sec: 20

retries:
  attempts: 2
  backoff_sec: 2
